-- Auto-generated SQL to fix ownership and territories
-- Generated on 2025-07-30T16:53:26.847Z
-- Based on external API data analysis

-- Create temporary tables
CREATE TEMP TABLE IF NOT EXISTS username_mapping (
    username TEXT PRIMARY KEY,
    user_id UUID NOT NULL,
    default_territory TEXT
);

CREATE TEMP TABLE IF NOT EXISTS org_owner_mapping (
    organization_name TEXT PRIMARY KEY,
    username TEXT NOT NULL
);

-- Insert user mappings
INSERT INTO username_mapping (username, user_id, default_territory) VALUES
    ('dread5', '08397158-4cf4-48df-875f-7501df5fac2d', 'Kingston'),
    ('seakah', 'b623f4e2-603f-47d8-9b68-7278a9edabea', 'Kingston'),
    ('flash', '6939f0a7-8bbf-4a01-91fb-7d2b21bc71e0', 'Kingston'),
    ('rogimon', '18e7177f-019f-40a0-98d6-34c5c0fa4cde', 'St. Ann'),
    ('charms', 'd97f2a98-3c6f-4ab8-b7c7-5e330d3edf45', 'Portland'),
    ('Chala', 'cffd914a-46a7-4748-bde5-0b7493cebdd8', 'St. Mary'),
    ('Tatiana_1', '97043190-97f5-43be-b3af-80e5ae386cb5', 'Kingston');

-- Insert organization-to-username mappings from external API
INSERT INTO org_owner_mapping (organization_name, username) VALUES
    ('test', 'flash'),
    ('Tie Di Knot (Shelle Tweedie)', 'rogimon'),
    ('D&R Performance Outlet', 'rogimon'),
    ('Astro Smart Electronics ', 'rogimon'),
    ('New Ocho Rios Pharmacy', 'rogimon'),
    ('Sweet RiRi''s Deli Bar', 'rogimon'),
    ('Caribbean Meats and Groceries', 'rogimon'),
    ('Banana Leaf Restaurant ', 'rogimon'),
    ('Computer Wizz', 'rogimon'),
    ('Prestige Phone Accessories ', 'rogimon'),
    ('Silver Sands Restaurant and Lounge', 'rogimon'),
    ('The Village Bar & Grill', 'rogimon'),
    ('Dumai Perfume Store ', 'rogimon'),
    ('Bay Spa', 'rogimon'),
    ('Sherwin Williams ', 'rogimon'),
    ('Projects & Hardware Ltd', 'rogimon'),
    ('New Windsor Pharmacy', 'rogimon'),
    ('Golden Peak Farm Store', 'rogimon'),
    ('Hq Pub', 'Chala'),
    ('Better Value Enterprise', 'Chala'),
    ('Venessa', 'Chala'),
    ('Tamara Walsh', 'Chala'),
    ('5 Star Bike Shop', 'Chala'),
    ('Palmetto Grove Farm Store', 'Chala'),
    ('Kishmar’s Bar', 'Chala'),
    ('Yvonne Bar & Grocery', 'Chala'),
    ('Flames ', 'Chala'),
    ('Beauty Statement', 'Chala'),
    ('Picture Perfect Hq', 'Chala'),
    ('Seggies Supermarket & Variety Store', 'Chala'),
    ('Ors Bridals', 'charms'),
    ('SSMC Express Internationsl', 'charms'),
    ('Chucks Hardware', 'charms'),
    ('Indulge your taste Buds ', 'Tatiana_1'),
    ('Consolidated bakeries Jamaica Ltd', 'Tatiana_1'),
    ('Cute & Palatable Pastries', 'Tatiana_1'),
    ('Jack’s bakery ', 'Tatiana_1'),
    ('SWIRLS ', 'Tatiana_1'),
    ('Sugar and Spice Ltd. ', 'Tatiana_1'),
    ('Susie’s ', 'Tatiana_1'),
    ('Totally Delicious Bakery ', 'Tatiana_1'),
    ('LynMax Bakery ', 'Tatiana_1'),
    ('Le Macaron Pastries and Desserts Jamaica ', 'Tatiana_1'),
    ('Leanne’s sweet tooth', 'Tatiana_1'),
    ('The bakery at spring ', 'Tatiana_1'),
    ('Maxfield Bakery & Pastries Ltd.', 'Tatiana_1'),
    ('National Bakery-half way tree wholesale ', 'Tatiana_1'),
    ('Fall in Chocolate ', 'Tatiana_1'),
    ('Mimimo ', 'Tatiana_1'),
    ('Eleni’s Bakery Jamaica ', 'Tatiana_1'),
    ('Pastries by Jan ', 'Tatiana_1'),
    ('Lola’s bakery cafe', 'Tatiana_1'),
    ('Devon House Bakery ', 'Tatiana_1'),
    ('Kids hair club salon ', 'Tatiana_1'),
    ('Totally male club spa & salon ', 'Tatiana_1'),
    ('First Lady’s beauty salon ', 'Tatiana_1'),
    ('Iconic Beauty bar ', 'Tatiana_1'),
    ('Open beauty divine spa ', 'Tatiana_1'),
    ('Salon Innovation ', 'Tatiana_1'),
    ('Kegars beauty and spa ', 'Tatiana_1'),
    ('Babies styles salon', 'Tatiana_1'),
    ('From head to fleek salon & spa ', 'Tatiana_1'),
    ('Lev Beauty Bar and Med Spa ', 'Tatiana_1'),
    ('Lizmel Pharmacy', 'rogimon'),
    ('Colour Shop Painter''s Studio', 'rogimon'),
    ('Select and Collect Fashion', 'rogimon'),
    ('R&J Pharmacy', 'rogimon'),
    ('Best Bargain Wholesale', 'rogimon'),
    ('Dazzle Fashion', 'rogimon'),
    ('Deli Cravz', 'rogimon'),
    ('Acon Supplies', 'rogimon'),
    ('Hairslau by Susan ', 'rogimon'),
    ('Lush Lavish Home Goods', 'rogimon'),
    ('Chloe''s Chic Loft', 'rogimon'),
    ('Romancing Fashion & Variety Store', 'rogimon'),
    ('Kemmax Sales & Distribution ', 'rogimon'),
    ('Perfect Choice Auto Parts', 'rogimon'),
    ('Genius Level Repairs & Accessories Services', 'rogimon'),
    ('Brown''s Town Dental', 'rogimon'),
    ('Inventive Supplies & Repairs', 'rogimon'),
    ('The Burlington Medical Centre', 'rogimon'),
    ('Brown''s Town Supermarket', 'rogimon'),
    ('SNM Creative Studio', 'rogimon'),
    ('MK Fashion and Gifts', 'rogimon'),
    ('Stay Fresh Taxi Service', 'rogimon'),
    ('White River Rafting', 'rogimon'),
    ('Silver Seas Hotel', 'rogimon'),
    ('AquaVille876', 'rogimon'),
    ('Food To Go', 'rogimon'),
    ('Greathouse Pharmacy ', 'rogimon'),
    ('Jian Pei Supermarket ', 'rogimon'),
    ('Sun Save Solar', 'rogimon'),
    ('BJs Bridal', 'rogimon'),
    ('Spark Sports', 'rogimon'),
    ('Comfort Systems Ltd', 'rogimon'),
    ('AC Vark Fire & Security', 'rogimon'),
    ('KBJ Cleaning Services', 'rogimon'),
    ('The Meat Place', 'rogimon'),
    ('Unicash Services', 'rogimon'),
    ('GAP Appliance Depot', 'rogimon'),
    ('Focused Opthalmics', 'rogimon'),
    ('Elite Luxe Salon & Spa', 'rogimon'),
    ('Valu-Life Pharmacy', 'rogimon'),
    ('Karibbean Korner Supermarket', 'Chala'),
    ('AML Building Supplies', 'rogimon'),
    ('Home Solutions Windows and Doors', 'rogimon'),
    ('Splash Car Wash', 'rogimon'),
    ('Top Secret Bar & Restaurant', 'rogimon'),
    ('Blake''s Car Rental', 'rogimon'),
    ('Drax Hall Physiotherapy & Rehab', 'rogimon'),
    ('Significant Electronics Ltd', 'rogimon'),
    ('Aletia''s Beauty Retreat', 'rogimon'),
    ('Golden Phoenix Restaurant', 'rogimon'),
    ('Papi Chulo', 'rogimon'),
    ('Drax Hall Family Dental', 'rogimon'),
    ('Kaya Herb House', 'rogimon'),
    ('Shangri-la Flower Shop', 'rogimon'),
    ('World of Doors & More', 'rogimon'),
    ('Simmond''s Hardware', 'rogimon'),
    ('Ignite Tech Consultancy', 'rogimon'),
    ('KAG Stockpile', 'rogimon'),
    ('High Seas Seafood Restaurant', 'rogimon'),
    ('L''Escargot', 'rogimon'),
    ('Canna Clinic', 'rogimon'),
    ('Evers Taxi & Tours', 'rogimon'),
    ('Travel With Class Booking Agency', 'rogimon'),
    ('Flavour''s Beach Bar', 'rogimon'),
    ('Cecille''s Garden & Wedding Centre ', 'rogimon'),
    ('Satchsie Tours', 'rogimon'),
    ('Queen V''s Supermarket', 'rogimon'),
    ('A Mi Fi Tell You Lounge & Grill', 'rogimon'),
    ('Sharkie''s See Food Restaurant', 'rogimon'),
    ('Sunshine Gifts & More', 'rogimon'),
    ('Dave''s Designer Depot', 'rogimon'),
    ('San San Supermarket', 'rogimon'),
    ('Dazzle', 'rogimon'),
    ('Bravo Dental & Medical', 'rogimon'),
    ('Lloyd’s Hardware', 'Tatiana_1'),
    ('Elwin’s Hardware ', 'Tatiana_1'),
    ('All you need hardware & supplies ', 'Tatiana_1'),
    ('Home& Things limited ', 'Tatiana_1'),
    ('Tools Hardware & Supplies ', 'Tatiana_1'),
    ('Total Hardware & supplies ', 'Tatiana_1'),
    ('Phill’s hardware ', 'Tatiana_1'),
    ('Lumber Depot', 'Tatiana_1'),
    ('H&L Rapid True Value ', 'Tatiana_1'),
    ('Super Valu Home Centre', 'Tatiana_1'),
    ('All Terrain Equipment & Parts Ltd', 'rogimon'),
    ('Candy''s Tips & Toes Salon', 'rogimon'),
    ('Ashman''s Equipment', 'rogimon'),
    ('Klimate Contractors', 'rogimon'),
    ('QDS Jamaica', 'rogimon'),
    ('SNAP', 'rogimon'),
    ('Splash Time Water Sports & Tours Ltd', 'rogimon'),
    ('Sports Unlimited', 'rogimon'),
    ('Square 1 Laundry & Dry Cleaning', 'rogimon'),
    ('SSS Courier', 'rogimon'),
    ('St. Monica''s College', 'rogimon'),
    ('Target Technologies', 'rogimon'),
    ('Taste of Jamaica Authentic Tours', 'rogimon'),
    ('Tech Smart Internet Cafe', 'rogimon'),
    ('The Achiever''s Sports & Trophies', 'rogimon'),
    ('The Lion House Jamaica', 'rogimon'),
    ('The Ochi Rios Signage and Printing Company', 'rogimon'),
    ('The Prescription Centre', 'rogimon'),
    ('Top Layer Produce Farm and Garden Supply', 'rogimon'),
    ('Total Tools', 'rogimon'),
    ('TruPower Industrial Solutions', 'rogimon'),
    ('Sand and Tan Beach Hotel', 'rogimon'),
    ('Maison Furniture & Accessories ', 'Tatiana_1'),
    ('Rockland furniture depot 41&1/2', 'Tatiana_1'),
    ('Rainbow Bargain Centre', 'Tatiana_1'),
    ('Living Spaces ', 'Tatiana_1'),
    ('Matahari Furniture | Home Accents ', 'Tatiana_1'),
    ('New City Furniture Co Ltd', 'Tatiana_1'),
    ('FurnitureLand & Karmen’s Kollection', 'Tatiana_1'),
    ('Spaces ', 'Tatiana_1'),
    ('Ashley Furniture Homestore ', 'Tatiana_1'),
    ('Active Home Centre', 'Tatiana_1'),
    ('Sadhwani''s Dental Care', 'rogimon'),
    ('S & S Refrigeration and Air Conditioning', 'rogimon'),
    ('Rika''s Delishus Treats', 'rogimon'),
    ('Reggae Pot Rastarant', 'rogimon'),
    ('Quality Contractors Depot', 'rogimon'),
    ('Pure Chocolate Jamaica', 'rogimon'),
    ('PRC Traders', 'rogimon'),
    ('Pool World & Fishing Supplies', 'rogimon'),
    ('Pine Grove Pharmacy', 'rogimon'),
    ('Oceans on the Ridge', 'rogimon'),
    ('NM Flash Errand Services', 'rogimon'),
    ('NJH Stationery Outlet', 'rogimon'),
    ('Nelson''s Signs & Printery', 'rogimon'),
    ('MyCart Express', 'rogimon'),
    ('Murae''s Creations', 'rogimon'),
    ('MTS Accounting & Business Solutions Limited', 'rogimon'),
    ('Motions Inc', 'rogimon'),
    ('Mongoose Restaurant', 'rogimon'),
    ('McCalla''s PLumbing Service', 'rogimon'),
    ('McBean''s Project Management', 'rogimon'),
    ('Massive Auto Parts', 'rogimon'),
    ('Mainland China Restaurant', 'rogimon'),
    ('Lavender Moon Villas', 'rogimon'),
    ('LaTouche Solutions Limited', 'rogimon'),
    ('Landmark Plaza', 'rogimon'),
    ('L & C Supermarket', 'rogimon'),
    ('Kyro Services', 'rogimon'),
    ('Karandas Tours', 'rogimon'),
    ('Joseph''s Ocho Rios', 'rogimon'),
    ('Jfross Tours', 'rogimon'),
    ('Jewels & Time Ocho Rios', 'rogimon'),
    ('Janih Tours', 'rogimon'),
    ('IWMS Jamaica', 'rogimon'),
    ('Island Wide Business Solutions', 'rogimon'),
    ('Island Radiology', 'rogimon'),
    ('Internet Cafe Printing and Design', 'rogimon'),
    ('Intense Fashion JA', 'rogimon'),
    ('Hydaniium Business Suites', 'rogimon'),
    ('Highway Electric', 'rogimon'),
    ('Hibiscus Lodge', 'rogimon'),
    ('Hi-Tech Innovative', 'rogimon'),
    ('Guhly Grafx', 'rogimon'),
    ('Graphixx Designz', 'rogimon'),
    ('Gifts Galore Bookshop', 'rogimon'),
    ('Gem Palace', 'rogimon'),
    ('Elliott''s Electronic Repair', 'rogimon'),
    ('Easi Parcel Ocho Rios', 'rogimon'),
    ('E-Jam Employment Jamaica', 'rogimon'),
    ('Drop Di Bass Entertainment', 'rogimon'),
    ('La Express Limited', 'rogimon'),
    ('Divi Wholesale Limited', 'rogimon'),
    ('Darkzide Studios', 'rogimon'),
    ('Cup-Cakolicious', 'rogimon'),
    ('CVL Financial and Management Service Limited', 'rogimon'),
    ('Computer Business Supplies (C.B.S)', 'rogimon'),
    ('Colour Plus Graphics & Printing', 'rogimon'),
    ('Coconut Grove Supermarket', 'rogimon'),
    ('Cash Genie Micro Loans', 'rogimon'),
    ('BNB Couriers', 'rogimon'),
    ('Big Ben Meats and Groceries', 'rogimon'),
    ('Bds Connections', 'rogimon'),
    ('Bandoo Events Solutions', 'rogimon'),
    ('Attire Jamaican style', 'rogimon'),
    ('ASAP Signs', 'rogimon'),
    ('Arysto Bling', 'rogimon'),
    ('Artworx876 Graphics', 'rogimon'),
    ('Apple Specialist by Sheldon', 'rogimon'),
    ('APEX Luxury WaterSports', 'rogimon'),
    ('All Signs Limited', 'rogimon'),
    ('Agape Courier Ocho Rios', 'rogimon'),
    ('Kamal''s Cambio & Superette', 'rogimon'),
    ('Oyaay Chicken and Fish', 'rogimon'),
    ('Anglers Restaurant ', 'rogimon'),
    ('Sea Salt Travel Ja', 'rogimon'),
    ('Spa Divine', 'Tatiana_1'),
    ('Kegars Beauty and Spa ', 'Tatiana_1'),
    ('Tranquility Day Spa', 'Tatiana_1'),
    ('Roxanna Salon', 'Tatiana_1'),
    ('Adam & Eve Day Spa ', 'Tatiana_1'),
    ('Bella Oasis Day Spa', 'Tatiana_1'),
    ('Spa Aesthetique', 'Tatiana_1'),
    ('Diva Salon & spa ', 'Tatiana_1'),
    ('Grog Shoppe Restaurant ', 'Tatiana_1'),
    ('Swing Cafe', 'Tatiana_1'),
    ('PRESS', 'Tatiana_1'),
    ('Backyard restaurant ', 'Tatiana_1'),
    ('Kingston reggae garden ', 'Tatiana_1'),
    ('Clubhouse Brewery ', 'Tatiana_1'),
    ('Janga’s soundbar & grill ', 'Tatiana_1'),
    ('Catch 22 lounge Ja ', 'Tatiana_1'),
    ('Oak wine bar & cocktail lounge ', 'Tatiana_1'),
    ('Lust lounge', 'Tatiana_1'),
    ('Di Lot restaurant & bar ', 'Tatiana_1'),
    ('Epican Tapas lounge ', 'Tatiana_1'),
    ('Signature lounge at SoSo seafood more & limited', 'Tatiana_1'),
    ('Blend bar & lounge ', 'Tatiana_1'),
    ('Cognac Bar and lounge ', 'Tatiana_1'),
    ('Movie star lounge', 'Tatiana_1'),
    ('Skybox bar and lounge ', 'Tatiana_1'),
    ('Rockendz ultra lounge ', 'Tatiana_1'),
    ('Ultimate ultra lounge & restaurant ', 'Tatiana_1'),
    ('Republic Jamaica ', 'Tatiana_1'),
    ('Mello sports bar and lounge ', 'Tatiana_1'),
    ('D’Lux restaurant & lounge ', 'Tatiana_1'),
    ('Sugar Plum', 'Tatiana_1'),
    ('Seven ultra lounge ', 'Tatiana_1'),
    ('Oxfordshire ultra lounge ', 'Tatiana_1'),
    ('Macau gaming lounge and bar ', 'Tatiana_1'),
    ('Regency bar & lounge ', 'Tatiana_1'),
    ('420 hookah lounge', 'Tatiana_1'),
    ('Dulce Lounge', 'Tatiana_1'),
    ('JPOK', 'Tatiana_1'),
    ('Starbucks', 'rogimon'),
    ('Restaurant For Your B,L&D', 'Chala'),
    ('New York Little Macy’s', 'Chala'),
    ('Melo Mart ', 'Chala'),
    ('Fiah Pot & Grill', 'Chala'),
    ('Boscobel Farm Supplies', 'Chala'),
    ('Boscobel Community & Pharmacy ', 'Chala'),
    ('Sir B Auto Parts', 'Chala'),
    ('Colonel’s Meats & More', 'Chala'),
    ('Tower Restaurant & Bar', 'Chala'),
    ('Michael GL Supermarket ', 'Chala'),
    ('Northcoast Seafood Outlet & Meatmart', 'Chala'),
    ('Alboe ', 'Chala'),
    ('Ship For Less', 'Chala'),
    ('Azure Ocean Grill', 'Chala'),
    ('Bim Bim Bar', 'Chala'),
    ('Prospect Sip N Chill', 'Chala'),
    ('Cos Penny Variety & Furniture Store', 'Chala'),
    ('The Bird’s Nest Bar & Grill', 'Chala'),
    ('AML Electrical Supplies', 'Chala'),
    ('White River Ranch ', 'Chala'),
    ('Home Solutions Windows & Doors', 'Chala'),
    ('Golden Gate Restaurant ', 'Tatiana_1'),
    ('Strings & Stones ', 'Tatiana_1'),
    ('Blend Bar & lounge ', 'Tatiana_1'),
    ('Rojo restaurant ', 'Tatiana_1'),
    ('The Oasis on the Oxford ', 'Tatiana_1'),
    ('Starbucks ', 'Tatiana_1'),
    ('Buzz Osteria Italiana ', 'Tatiana_1'),
    ('Triple Century Sports Bar ', 'Tatiana_1'),
    ('Waterfall ', 'Tatiana_1'),
    ('Thiiah’s Juice and Organic Foods-Liguanea ', 'Tatiana_1'),
    ('Thai Sticks restaurant ', 'Tatiana_1'),
    ('Zoleah Cafe ', 'Tatiana_1'),
    ('Kaya Pizza ', 'Tatiana_1'),
    ('Courtyard 71 restaurant ', 'Tatiana_1'),
    ('Y not Pita ', 'Tatiana_1'),
    ('Annex East Japanese ', 'Tatiana_1'),
    ('Jojo’s Jerk Pit ', 'Tatiana_1'),
    ('Progressive Shopping Center ', 'Tatiana_1'),
    ('The Healthy Cafe Ja ', 'Tatiana_1'),
    ('Veganly Vegetarian Cafe ', 'Tatiana_1'),
    ('Uncorked Too ', 'Tatiana_1'),
    ('Doublepamls bar & lounge ', 'Tatiana_1'),
    ('Golden Bowl Restaurant', 'Tatiana_1'),
    ('Kingston Dub Club ', 'Tatiana_1'),
    ('WellSpring Raw Juices', 'Tatiana_1'),
    ('Veggie Campus ', 'Tatiana_1'),
    ('Tempo Cafe ', 'Tatiana_1'),
    ('Footprints Cafe|restaurant & lounge ', 'Tatiana_1'),
    ('Cafe Hibiscus ', 'Tatiana_1'),
    ('Sweet Vegan Cafe ', 'Tatiana_1'),
    ('Yummy Cafe Barbican ', 'Tatiana_1'),
    ('TGI Fridays ', 'Tatiana_1'),
    ('Domino’s Liguanea ', 'Tatiana_1'),
    ('Mango Tree restaurant ', 'Tatiana_1'),
    ('Silli Chili restaurant ', 'Tatiana_1'),
    ('Dragon Court Restaurant  ', 'Tatiana_1'),
    ('Fusion Multicultural Cuisine ', 'Tatiana_1'),
    ('Bombay Darbar by Nirvanna ', 'Tatiana_1'),
    ('Island Vibz restaurant ', 'Tatiana_1'),
    ('Charlene’s Ackeespot ', 'Tatiana_1'),
    ('South Avenue Grill ', 'Tatiana_1'),
    ('Tea Tree Creperie restaurant ', 'Tatiana_1'),
    ('Blue Window restaurant ', 'Tatiana_1'),
    ('Nikki’s kitchen @ Dulce Lounge ', 'Tatiana_1'),
    ('Tai Tai Ice Cream Roll Cafe ', 'Tatiana_1'),
    ('Jimbilins', 'Tatiana_1'),
    ('Cafe El Centro ', 'Tatiana_1'),
    ('Alexander’s Restaurant ', 'Tatiana_1'),
    ('Little India ', 'Tatiana_1'),
    ('Sweetwood Jerk Joint ', 'Tatiana_1'),
    ('Toss and Roll Salad Bar ', 'Tatiana_1'),
    ('Sizzlin’Pizza ', 'Tatiana_1'),
    ('Zen Bowls ', 'Tatiana_1'),
    ('PINYATAS Lounge Restaurant Bar & Jerk Center', 'Tatiana_1'),
    ('Paladar restaurant ', 'Tatiana_1'),
    ('The Steak House on the Verandah ', 'Tatiana_1'),
    ('CHILLIN’ restaurant and bar ', 'Tatiana_1'),
    ('Chester’s Chicken ', 'Tatiana_1'),
    ('TACBAR restaurant ', 'Tatiana_1'),
    ('WingKing Jamaica ', 'Tatiana_1'),
    ('Coal Fire ', 'Tatiana_1'),
    ('New Palm Restaurant ', 'Tatiana_1'),
    ('24 Seven Cafe ', 'Tatiana_1'),
    ('Tamarind Indian Cuisine ', 'Tatiana_1'),
    ('Fromage Bisto ', 'Tatiana_1'),
    ('Tastee Liguanea ', 'Tatiana_1'),
    ('CRU Bar and Kitchen ', 'Tatiana_1'),
    ('Pushpa’s Indian restaurant ', 'Tatiana_1'),
    ('Kingston Jerk ', 'Tatiana_1'),
    ('Mother’s ', 'Tatiana_1'),
    ('The Rib Kage Grill restaurant ', 'Tatiana_1'),
    ('Tree Bark ', 'Tatiana_1'),
    ('Cannonball Cafe sovereign north ', 'Tatiana_1'),
    ('New Leaf Vegetarian restaurant ', 'Tatiana_1'),
    ('Chez Maria Restaurant ', 'Tatiana_1'),
    ('New Imperial Court restaurant ', 'Tatiana_1'),
    ('Northside Kitchen ', 'Tatiana_1'),
    ('Ribbiz UltraLounge ', 'Tatiana_1'),
    ('Chive Restaurant Jamaica ', 'Tatiana_1'),
    ('22 Jerk', 'Tatiana_1'),
    ('Tava Indian Fusion ', 'Tatiana_1'),
    ('Bamboo Bar & lounge ', 'Tatiana_1'),
    ('TRIO', 'Tatiana_1'),
    ('Brew’d Awakenings ', 'Tatiana_1'),
    ('Lawson’s Smoke House', 'Tatiana_1'),
    ('Ambassador Bar & Grill', 'Tatiana_1'),
    ('Summer Palace Restaurant ', 'Tatiana_1'),
    ('Falafel House ', 'Tatiana_1'),
    ('Taurus Garden Chinese Restaurant ', 'Tatiana_1'),
    ('Uncorked! Restaurant ', 'Tatiana_1'),
    ('The Ref ', 'Tatiana_1'),
    ('Sea Deck Restaurant & Lounge', 'Tatiana_1'),
    ('Chilitos Jamexican Food ', 'Tatiana_1'),
    ('Ravaz Kitchen ', 'Tatiana_1'),
    ('Sora Japanese Sky Cuisine ', 'Tatiana_1'),
    ('Broken Plate Restaurant ', 'Tatiana_1'),
    ('Orchid Thai ', 'Tatiana_1'),
    ('Dulce Lounge ', 'Tatiana_1'),
    ('Palace Cineplex', 'Tatiana_1'),
    ('KFC sovereign center', 'Tatiana_1'),
    ('Cafe Blue sovereign center', 'Tatiana_1'),
    ('Digicel ', 'Tatiana_1'),
    ('Fatboy Sandwich house', 'Tatiana_1'),
    ('Deli works ', 'Tatiana_1'),
    ('Mac Cosmetics ', 'Tatiana_1'),
    ('Fish Pot sovereign center', 'Tatiana_1'),
    ('Monarch Pharmacy ', 'Tatiana_1'),
    ('Earth Retail Ja', 'Tatiana_1'),
    ('Lee’s Fifth Avenue sovereign ', 'Tatiana_1'),
    ('Trafalgar Travel-sovereign center ', 'Tatiana_1'),
    ('Vision Plus Optical ', 'Tatiana_1'),
    ('Ammar’s ', 'Tatiana_1'),
    ('Shoeaholics Jamaica', 'Tatiana_1'),
    ('Green Hills Natural Foods', 'Tatiana_1'),
    ('Wide Smiles Dental', 'Chala'),
    ('Chicken Hut', 'Chala'),
    ('Fitness Physique', 'Chala'),
    ('Siding Town Shop', 'Chala'),
    ('Span Yard Service Centre', 'Chala'),
    ('S&V Hardware', 'Chala'),
    ('The Flames Restaurant ', 'Chala'),
    ('100 Restaurant ', 'Tatiana_1'),
    ('Sovereign supermarket ', 'Tatiana_1'),
    ('General foods ', 'Tatiana_1'),
    ('Morgan’s Creek ', 'Tatiana_1'),
    ('Tulloch’s Auto', 'Chala'),
    ('Lifestyle clothes store', 'Tatiana_1'),
    ('Steel Horizon Gym', 'Chala'),
    ('Answers for children ', 'Tatiana_1'),
    ('Manii Aesthetics Fitness Centre', 'Chala'),
    ('Jade Gardens restaurants ', 'Tatiana_1'),
    ('Tutti fruitti ', 'Tatiana_1'),
    ('Tip tip Wholesale', 'Chala'),
    ('YAO restaurant sovereign ', 'Tatiana_1'),
    ('Galina Breeze', 'Chala'),
    ('Jamaica Juice ', 'Tatiana_1'),
    (' Little Tokyo ', 'Tatiana_1'),
    ('D&R Woodcraft Traders', 'Chala'),
    ('Sizzlin (pizza,pasta and more)', 'Tatiana_1'),
    ('Better Wheels Auto Ltd', 'Chala'),
    ('LBJ Hardware', 'Chala'),
    ('Innovative superstore ', 'Tatiana_1'),
    ('Goldmine Jewellers', 'Tatiana_1'),
    ('Sports Craze ', 'Tatiana_1'),
    ('Sizzlin’ Grill ', 'Tatiana_1'),
    ('Island grill ', 'Tatiana_1'),
    ('Pastry Passion store', 'Tatiana_1'),
    ('Sangster Book Store Limited', 'Tatiana_1'),
    ('Crocs Kingston Jamaica', 'Tatiana_1'),
    ('Diva Spa', 'Tatiana_1'),
    ('Swings Bar & Lounge ', 'Chala'),
    ('Winter''s Petroleum', 'Chala'),
    ('Kkb''s Shipping', 'Chala'),
    ('Richard Pepper Pot', 'Chala'),
    ('D&D meat & more ', 'charms'),
    ('NAKDEM', 'charms'),
    ('Actual call Centre', 'charms'),
    ('Landos Chemicals', 'charms'),
    ('Delicious Delight', 'charms'),
    ('Wilson''s  Electric  supplies & tool rental', 'charms'),
    ('Sshordee’s Beauty Studio', 'Chala'),
    ('Klassy Kasuals', 'Chala'),
    ('Cande Courier ', 'Chala'),
    ('Highgate Ultimate Hair & Nail Salon', 'Chala'),
    ('Supremacy Ice and Water Store', 'Chala'),
    ('The New Highgate Pharmacy', 'Chala'),
    ('Techni Shack', 'Chala'),
    ('Trendified Nail Care & Mua', 'Chala'),
    ('Proud Wear Jewelry by Meka', 'Chala'),
    ('Blahk Inkk', 'Chala'),
    ('Rhiii Cosmetics', 'Chala'),
    ('Slayed by Ai', 'Chala'),
    ('Beatz by Shan', 'Chala'),
    ('Swim Pieces Ja', 'Chala'),
    ('Sweety’s Beauty Hub', 'Chala'),
    ('Level Up Lounge', 'Chala'),
    ('Triangle Sports Bar & Grill', 'Chala'),
    ('Phoenix Vision Centre', 'Chala'),
    ('Trafalgar Travel Ltd', 'Chala'),
    ('Cabarita Inn & Grill', 'Chala'),
    ('Monique''s Collections', 'Chala'),
    ('Melanin Boutique ', 'Chala'),
    ('Lash Deluxee', 'Chala'),
    ('MiniXquisite Lashes', 'Chala'),
    ('Unique Snapshotz', 'Chala'),
    ('St. Mary Seafood & Lounge', 'Chala'),
    ('Ubee Beauty & Gift', 'Chala'),
    ('Boswell’s Hardware ', 'Chala'),
    ('Palm Aire Supermarket', 'Chala'),
    ('T&G Shipping Company ', 'Chala'),
    ('Bob’s Supercentre Ltd', 'Chala'),
    ('Affordable books & things', 'charms'),
    ('Foodies restaurant', 'charms'),
    ('VIP  Jewellers', 'charms'),
    ('New Attraction wholesale', 'charms'),
    ('VIP Hardware', 'charms'),
    ('Easyern farm store & farm supplies', 'charms'),
    ('Boshavel variety store', 'charms'),
    ('Seafood metas & more', 'charms'),
    ('Portland Jerk centre & restsurant', 'charms'),
    ('Seaview metas groceries& seasoning', 'charms'),
    ('Pizza cade  ( Italian)', 'charms'),
    ('SB printers', 'charms'),
    ('The Pink Drinks & liquor wholesale', 'charms'),
    ('Central meats & groceries ', 'charms'),
    ('Easi Projects hardware & party store', 'charms'),
    ('Di Gazobo restaurant', 'charms'),
    ('Ramtullas super centre', 'charms'),
    ('Flavors skin care ', 'charms'),
    ('Fireman''s auto  parts &supplies ', 'charms'),
    ('Survival vegetarian  restaurant ', 'charms'),
    ('Piggy''s jersey centre', 'charms'),
    ('Astro Book shop & stationary', 'charms'),
    ('Arlene & Elaine Rx', 'charms'),
    ('Hiz fashion', 'charms'),
    ('Kamma''s wholesale retail', 'charms'),
    ('Stationary Baby & cosmetics ', 'charms'),
    ('Blu Diamond jewellers', 'charms'),
    ('Men''s ladies & children''s wear', 'charms'),
    ('Supermodel pharmacy', 'charms'),
    ('Petals  variety store', 'charms'),
    ('Princess wholesale &groceries ', 'charms'),
    ('Carib hardware &electrical  supplies ', 'charms'),
    ('Cat Gas', 'charms'),
    ('KB tyre''s & auto parts', 'charms'),
    ('Auh-soj car rental', 'charms'),
    ('Lighting  Plumbing electrical  & more', 'charms'),
    ('Richard Auto service  centre', 'charms'),
    ('Sir Bert''s  pastries & natural juices', 'charms'),
    ('Shan''s', 'charms'),
    ('Savi''s cook shop', 'charms'),
    ('Start well cook shop', 'charms'),
    ('East Port farm &general supplies', 'charms'),
    ('Chucks harberdashery', 'charms'),
    ('Sharla''s', 'charms'),
    ('Freshco supermarket ', 'charms'),
    ('Shipwize', 'charms'),
    ('Inna Medical centre', 'charms'),
    ('Broadband vision eye care', 'charms'),
    ('Taj Pharmacy', 'charms'),
    ('Pj expect  more pay less furniture store', 'charms'),
    ('Auh chill grill', 'charms'),
    ('Tina Wholesale ', 'Chala'),
    ('Berser ', 'Tatiana_1'),
    ('Answer Gifts and home center ', 'Tatiana_1'),
    ('Tropical Appliances furniture ', 'Tatiana_1'),
    ('Anne Martin ', 'Tatiana_1'),
    ('Body Studio ', 'Tatiana_1'),
    ('Cell City ', 'Tatiana_1'),
    ('Insight Optical ', 'Tatiana_1'),
    ('Express Fitness-Jonathan Greene', 'Tatiana_1'),
    ('Creep ‘n’ Closet- Brihannia ', 'Tatiana_1'),
    ('Tech World- Damion Chong ', 'Tatiana_1'),
    ('Faithful Homes Decor- Jenelle ', 'Tatiana_1'),
    ('Susie’s', 'Tatiana_1'),
    ('Brit Bran Fashion ', 'Tatiana_1'),
    ('Craft Cottage ', 'Tatiana_1'),
    ('Imuse ', 'Tatiana_1'),
    ('Fabulous Trends ', 'Tatiana_1'),
    ('Fabulous Trends', 'Tatiana_1'),
    ('The Style Palace ', 'Tatiana_1'),
    ('I’m Waxed- Chevelle ', 'Tatiana_1'),
    ('Enigma and Men’s Grooming Lounge (same owner)', 'Tatiana_1'),
    ('Glam Beauty Studio ', 'Tatiana_1'),
    ('Royale Jewellers-George', 'Tatiana_1'),
    ('Watts New', 'Tatiana_1'),
    ('Lee’s Fifth Avenue-Sangster', 'Tatiana_1'),
    ('Popin Jamaica ', 'Tatiana_1'),
    ('Western Sports-Matthew Pringle ', 'Tatiana_1'),
    ('Proactive Health Store-Dean ', 'Tatiana_1'),
    ('Woolworth-Ms Williams', 'Tatiana_1'),
    ('Kook Bella', 'Tatiana_1'),
    ('Child’s Play ', 'Tatiana_1'),
    ('Closet Cloud ', 'Tatiana_1'),
    ('American Jewellery Co.', 'Tatiana_1'),
    ('Phoenix Eye Care', 'Tatiana_1'),
    ('Artique ', 'Tatiana_1'),
    ('Singer ', 'Tatiana_1'),
    ('Collectibles ', 'Tatiana_1'),
    ('Ammers ', 'Tatiana_1'),
    ('Teethetics Jamaica ', 'Tatiana_1'),
    ('Rituals coffee house ', 'Tatiana_1'),
    ('Emanvelle Boutique ', 'Tatiana_1'),
    ('Land Clothing Store', 'Tatiana_1'),
    ('Martina’s Nail Place', 'Tatiana_1'),
    ('Brides Place', 'Tatiana_1'),
    ('Manhattan Cloth and Shoes', 'Tatiana_1'),
    ('Sammy’s feet', 'Tatiana_1'),
    ('Answers (kids clothing)', 'Tatiana_1'),
    ('Berger Paint', 'Tatiana_1'),
    ('Living Foods', 'Tatiana_1'),
    ('Kix', 'Tatiana_1'),
    ('Bridges (clothing)', 'Tatiana_1'),
    ('Triphina’s Pharmacy ', 'Tatiana_1'),
    ('Giant Family Mart', 'Chala'),
    ('Betta Way Enterprise', 'Chala'),
    ('Nails by Rissa', 'Chala'),
    ('All P’s Bakery', 'Chala'),
    ('Marcore Shipping', 'Chala'),
    ('Fresh Fashion', 'Chala'),
    ('Kutella Kosmetics', 'Chala'),
    ('Inkmi Group', 'Chala'),
    ('Skymar’s Hardware', 'Chala'),
    ('Christine Fast Food & Smoothie', 'Chala'),
    ('Okera Distribution Ltd', 'Chala'),
    ('Nu Millenium Pharmacy', 'Chala'),
    ('Remedial Pharmacy ', 'Chala'),
    ('Fabian Hardware', 'Chala'),
    ('Z Parts', 'Chala'),
    ('Dahlia’s Bar', 'Chala'),
    ('Obsidian Bar and Lounge', 'Chala'),
    ('Christian Shop', 'Chala'),
    ('Desmond Hardware', 'Chala'),
    ('Becky Hair Salon', 'Chala'),
    ('Car Car’s Liquor Store', 'Chala'),
    ('Unique Nails by Deanna', 'Chala'),
    ('Tumpa Barbershop', 'Chala'),
    ('Silly Cable Shop', 'Chala'),
    ('B & E', 'Tatiana_1'),
    ('Blu Mobile ', 'Tatiana_1'),
    ('Royale Carriage ', 'Tatiana_1'),
    ('Sneakers Express ', 'Tatiana_1'),
    ('Bliss Dental ', 'Tatiana_1'),
    ('Salon Empora ', 'Tatiana_1'),
    ('Carby’s Souevnir ', 'Tatiana_1'),
    ('Carby’s Clothing ', 'Tatiana_1'),
    ('Southdale Hardware and Glass', 'Tatiana_1'),
    ('Fashion Affair ', 'Tatiana_1'),
    ('Deli Kez Decor', 'Tatiana_1'),
    ('Kids Kraze ', 'Tatiana_1'),
    ('Jah Mow Kitchen', 'charms'),
    ('Soupie Restaurant', 'charms'),
    ('Pings corner groceries ', 'charms'),
    ('Total Beauty Supplies', 'charms'),
    ('Kings Restaurant', 'charms'),
    ('Duncan''s Rental and Car  Wash', 'charms'),
    ('Munchies Magic Touch', 'charms'),
    ('Eat more Meat', 'charms'),
    ('Little Portie', 'charms'),
    ('Living Food and Juices', 'Tatiana_1'),
    ('Kingston night market ', 'Tatiana_1'),
    ('Dubwise Cafe', 'Tatiana_1'),
    ('Dunn’s Electrical and Lighting', 'Tatiana_1'),
    ('Miss Vadnie', 'charms'),
    ('Peats ', 'charms'),
    ('Buff Bay Texaco', 'charms'),
    ('Degrees Green Grocery', 'charms'),
    ('Pam Shop', 'charms'),
    ('Kar shop', 'charms'),
    ('Jackie Shop', 'charms'),
    ('Polly Shop', 'charms'),
    ('Maureen shop', 'charms'),
    ('Shirley Shop', 'charms'),
    ('Janice Shop', 'charms'),
    ('Pat''s Meats', 'charms'),
    ('Stress free wholesale', 'charms'),
    ('C Max wholesale', 'charms'),
    ('Bill corner shop', 'charms'),
    ('Garnett Barbershop ', 'Chala'),
    ('Shyann Bar and Restaurant ', 'Chala'),
    ('Mullo Bar', 'Chala'),
    ('Bruff Cookshop', 'Chala'),
    ('Quest', 'Chala'),
    ('R&D Liqour Store ', 'Chala'),
    ('Oneil’s Hardware', 'Chala'),
    ('Sheka Nails', 'Chala'),
    ('Clavelia Classy Nails', 'Chala'),
    ('Face Cafe Beauty Bar', 'Chala'),
    ('Spanish Fly Lounge & Gaming', 'Chala'),
    ('Young Lee Supermarket ', 'Chala'),
    ('Gullu Meat Shop', 'Chala'),
    ('Dukie Meat Shop', 'Chala'),
    ('One Stop Haberdashery ', 'Chala'),
    ('Pem Pem Bar ', 'Chala'),
    ('Davis Photo Studio', 'Chala'),
    ('Elite Deli', 'Chala'),
    ('Mario Veggie Stop', 'Chala'),
    ('Ultimate Dinning Returant ', 'Tatiana_1'),
    ('Emmanuel’s Kitchen, Mr Emmanuel ', 'Tatiana_1'),
    ('Samfo Meats, Paul Lyn ', 'Tatiana_1'),
    ('Christiana Pharmacy and Book Store, Christopher Green', 'Tatiana_1'),
    ('Owen Watson', 'charms'),
    ('John O''Sullivan', 'charms'),
    ('Audrey Biggs', 'charms'),
    ('Deneisha', 'charms'),
    ('Gavin Blake', 'charms'),
    ('Patricia Wilson', 'charms'),
    ('Owen Thomas', 'charms'),
    ('James Trading ', 'Chala'),
    ('Postage Logistics Group', 'Chala'),
    ('Street Crave', 'Chala'),
    ('Janet Campbell ', 'charms'),
    ('Debeica Dawkins ', 'charms'),
    ('Ann Marie Pryce ', 'charms'),
    ('Kemisha Wallace ', 'charms'),
    ('Sophia Hayles', 'charms'),
    ('Jemmarie Pryce ', 'charms'),
    ('Michelle Williams ', 'charms'),
    ('Jean Pinnock', 'charms'),
    ('Jacqueline Laidley', 'charms'),
    ('Calvin Cargill ', 'charms'),
    ('Janet Jackson-Lyle ', 'charms'),
    ('Audine Dyce Richards', 'charms'),
    ('Jason Peat Hardware ', 'charms'),
    ('Diversity Farm & Garden Supplies ', 'charms'),
    ('Esther Johnson ', 'charms'),
    ('Keamba Brown', 'charms'),
    ('Scheme Unit HQ', 'charms'),
    ('Donnette Harrison ', 'charms'),
    ('Carol Ragbar', 'charms'),
    ('Zoe Hibberts', 'charms'),
    ('Hart Hill Shop & Save', 'charms'),
    ('Styled by T / Sashara Phipps', 'Chala'),
    ('Cellsmartsolution / Cassandra Riley', 'Chala'),
    ('Maffy’s New&Used Parts', 'Chala'),
    ('Racky Rentals/Akeem Thompson', 'Chala'),
    ('Blingerz Furniture Store', 'Chala'),
    ('W.C Best Deal Importers Limited', 'Chala'),
    ('Icecream and Sweeticious Pastry', 'Chala'),
    ('KCL Cyber Centre/ Kelly Lewis', 'Chala'),
    ('Protocol / Nahjay Hibbert', 'Chala'),
    ('World Connect Ja/Steven ', 'Chala'),
    ('Esco Mini Mart', 'Chala'),
    ('French Design/Kristoff Smith', 'Chala'),
    ('Taste Di Flava/Davian Morrison ', 'Chala'),
    ('Plick Print/Dennis Johnson', 'Chala'),
    ('Deliveryboss1876/Shavaughn Stephens ', 'Chala'),
    ('Stashia Skincare/Suwane Simms ', 'Chala'),
    ('Zana’s Seafood', 'Chala'),
    ('Gold Reign Beauty Supplies/Paula Minott', 'Chala'),
    ('William Supermarket/William Liao', 'Chala'),
    ('Hair by Landy Zee/Davia Cruickshank', 'Chala'),
    ('Nas Chem Supplies', 'Chala'),
    ('Davis Food Mart/Collin Davis', 'Chala'),
    ('Sister’s Salon/Shaneka Shand', 'Chala'),
    ('Shammy’s Hotspot/Shamoya Mitchell', 'Chala'),
    ('Hair with Flair/Natifa Hinds', 'Chala'),
    ('Peats', 'charms');

-- Update deals with missing owners
WITH matched_deals AS (
    SELECT 
        d.id as deal_id,
        um.user_id,
        um.default_territory
    FROM deals d
    LEFT JOIN organizations o ON d.organization_id = o.id
    JOIN org_owner_mapping om ON (
        om.organization_name = d.name 
        OR om.organization_name = o.name
    )
    JOIN username_mapping um ON um.username = om.username
    WHERE d.owner_id IS NULL
)
UPDATE deals d
SET 
    owner_id = md.user_id,
    created_by_id = COALESCE(d.created_by_id, md.user_id),
    updated_at = NOW()
FROM matched_deals md
WHERE d.id = md.deal_id;

-- Update organizations with missing territories
WITH org_updates AS (
    SELECT DISTINCT
        o.id as org_id,
        um.default_territory
    FROM organizations o
    JOIN deals d ON d.organization_id = o.id
    JOIN username_mapping um ON d.owner_id = um.user_id
    WHERE o.state_province IS NULL OR o.state_province = ''
)
UPDATE organizations o
SET 
    state_province = ou.default_territory,
    updated_at = NOW()
FROM org_updates ou
WHERE o.id = ou.org_id;

-- Additional update for organizations based on name matching
UPDATE organizations o
SET 
    state_province = um.default_territory,
    updated_at = NOW()
FROM org_owner_mapping om
JOIN username_mapping um ON um.username = om.username
WHERE 
    o.name = om.organization_name
    AND (o.state_province IS NULL OR o.state_province = '');

-- Report results
DO $$
DECLARE
    updated_deals INT;
    updated_orgs INT;
    remaining_deals INT;
    remaining_orgs INT;
BEGIN
    GET DIAGNOSTICS updated_deals = ROW_COUNT;
    
    SELECT COUNT(*) INTO remaining_deals FROM deals WHERE owner_id IS NULL;
    SELECT COUNT(*) INTO remaining_orgs FROM organizations WHERE state_province IS NULL OR state_province = '';
    
    RAISE NOTICE 'Update complete:';
    RAISE NOTICE '  Deals still without owners: %', remaining_deals;
    RAISE NOTICE '  Organizations still without territories: %', remaining_orgs;
END $$;

-- Clean up
DROP TABLE IF EXISTS username_mapping;
DROP TABLE IF EXISTS org_owner_mapping;
